<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { emptyAgentPage, agentDateLabel, type AgentApi, type AgentOperator, type AgentOperatorCandidate, type Company } from '../lib/agentWorkbench'
import AgentPagination from './AgentPagination.vue'
const props=defineProps<{api:AgentApi}>()
const rows=ref(emptyAgentPage<AgentOperator>()), candidates=ref<AgentOperatorCandidate[]>([]), companies=ref<Company[]>([]), query=ref(''), loading=ref(false),busy=ref(false),error=ref(''),success=ref('')
const form=reactive({sysUserId:0,merchantCustomerId:0,active:true}), selectedUser=ref<AgentOperatorCandidate|null>(null)
async function load(page=1){loading.value=true;try{rows.value=await props.api.fetchOperators({page,pageSize:20,query:query.value})}catch(e){error.value=e instanceof Error?e.message:'账号绑定加载失败。'}finally{loading.value=false}}
async function searchUsers(query=''){try{candidates.value=(await props.api.fetchOperatorCandidates({query,page:1,pageSize:50})).items}catch(e){error.value=e instanceof Error?e.message:'可绑定账号加载失败。'}}
async function searchCompanies(query=''){try{companies.value=(await props.api.fetchCompanies({query,page:1,pageSize:50})).items}catch(e){error.value=e instanceof Error?e.message:'企业加载失败。'}}
function edit(row:AgentOperator){form.sysUserId=row.sysUserId;form.merchantCustomerId=row.merchantCustomerId;form.active=row.active;selectedUser.value={sysUserId:row.sysUserId,userName:row.userName,nickName:row.nickName};if(!companies.value.some(company=>company.id===row.merchantCustomerId))companies.value.push({id:row.merchantCustomerId,companyName:row.companyName,displayName:row.companyName,email:''})}
async function save(){if(busy.value||!form.sysUserId||!form.merchantCustomerId)return;busy.value=true;error.value='';success.value='';try{await props.api.updateOperator(form.sysUserId,{merchantCustomerId:form.merchantCustomerId,active:form.active});success.value=form.active?'代理后台账号绑定已保存。':'代理后台账号绑定已停用。';await load(rows.value.page);await searchUsers()}catch(e){error.value=e instanceof Error?e.message:'账号绑定保存失败。'}finally{busy.value=false}}
onMounted(()=>Promise.all([load(),searchUsers(),searchCompanies()]))
</script>
<template><section data-testid="agent-operators-panel"><el-alert v-if="error" :title="error" type="error" :closable="false" /><el-alert v-if="success" :title="success" type="success" :closable="false" /><el-form :inline="true" @submit.prevent="load()"><el-form-item label="搜索绑定"><el-input v-model="query" clearable placeholder="账号或企业名称" /></el-form-item><el-form-item><el-button native-type="submit" :loading="loading">搜索</el-button></el-form-item></el-form><el-table :data="rows.items" border><el-table-column prop="userName" label="后台账号" /><el-table-column prop="nickName" label="姓名" /><el-table-column prop="companyName" label="代理企业" min-width="180" /><el-table-column label="状态"><template #default="{row}">{{row.active?'已启用':'已停用'}}</template></el-table-column><el-table-column label="更新时间" min-width="170"><template #default="{row}">{{agentDateLabel(row.updatedAt)}}</template></el-table-column><el-table-column label="操作" width="80"><template #default="{row}"><el-button link type="primary" :disabled="busy" @click="edit(row)">编辑</el-button></template></el-table-column></el-table><AgentPagination v-bind="rows" :disabled="loading||busy" @change="load" /><el-divider>绑定代理后台账号</el-divider><el-form label-position="top" :disabled="busy" @submit.prevent="save"><el-form-item label="后台账号"><el-select v-model="form.sysUserId" filterable remote :remote-method="searchUsers" placeholder="搜索无平台管理权限的后台账号" style="width:100%" data-testid="agent-operator-user"><el-option v-if="selectedUser&&!candidates.some(user=>user.sysUserId===selectedUser?.sysUserId)" :value="selectedUser.sysUserId" :label="`${selectedUser.userName} · ${selectedUser.nickName}`" /><el-option v-for="user in candidates" :key="user.sysUserId" :value="user.sysUserId" :label="`${user.userName} · ${user.nickName}`" /></el-select></el-form-item><el-form-item label="所属代理企业"><el-select v-model="form.merchantCustomerId" filterable remote :remote-method="searchCompanies" placeholder="搜索代理企业" style="width:100%" data-testid="agent-operator-company"><el-option v-for="company in companies" :key="company.id" :value="company.id" :label="company.companyName||company.displayName" /></el-select></el-form-item><el-form-item><el-switch v-model="form.active" active-text="允许此账号操作该企业" /></el-form-item><el-button type="primary" native-type="submit" :loading="busy" :disabled="!form.sysUserId||!form.merchantCustomerId" data-testid="agent-save-operator">保存绑定</el-button></el-form></section></template>
