<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useAgentApi, useAgentActions, type CustomerAddress } from '../lib/agentWorkbench'
const api = useAgentApi(), rows = ref<CustomerAddress[]>([]), editing = ref(false), editId = ref<number | null>(null), loading = ref(false)
const blank = () => ({ label: '', contactName: '', contactPhone: '', addressLine1: '', addressLine2: '', city: '', region: '', postalCode: '', country: '', defaultAddress: false })
const form = ref(blank()), { busy, error, success, run } = useAgentActions()
async function load() { loading.value = true; try { rows.value = await api.fetchCustomerAddresses() } catch (e) { error.value = e instanceof Error ? e.message : '地址加载失败。' } finally { loading.value = false } }
function edit(row?: CustomerAddress) { editId.value = row?.id || null; form.value = row ? { label: row.label, contactName: row.contactName, contactPhone: row.contactPhone, addressLine1: row.addressLine1, addressLine2: row.addressLine2 || '', city: row.city, region: row.region || '', postalCode: row.postalCode, country: row.country, defaultAddress: row.defaultAddress } : blank(); editing.value = true }
async function save() { const payload = { ...form.value }; if (await run(`address:${editId.value || 'create'}`, payload, key => api.saveAddress(editId.value, payload, key), () => { editing.value = false }, '代理返程地址已保存。')) await load() }
onMounted(load)
</script>
<template><section data-testid="agent-addresses-panel"><div class="agent-toolbar"><h2>代理返程地址</h2><el-button type="primary" :disabled="busy" data-testid="agent-new-address" @click="edit()">新增地址</el-button></div><p class="muted-copy">NXR 完成评级后，将整批卡片寄至所选代理地址。</p><el-alert v-if="error" :title="error" type="error" :closable="false" /><el-alert v-if="success" :title="success" type="success" :closable="false" /><p v-if="loading">加载中…</p><div v-else class="agent-address-list"><article v-for="row in rows" :key="row.id" class="agent-stock-card"><div class="agent-toolbar"><strong>{{ row.label }}{{ row.defaultAddress ? ' · 默认地址' : '' }}</strong><el-button :disabled="busy" @click="edit(row)">编辑</el-button></div><p>{{ row.contactName }} · {{ row.contactPhone }}</p><p>{{ [row.country,row.region,row.city,row.addressLine1,row.addressLine2,row.postalCode].filter(Boolean).join(' · ') }}</p></article><el-empty v-if="!rows.length" description="暂无代理返程地址" /></div><form v-if="editing" class="portal-form agent-operation" data-testid="agent-address-form" @submit.prevent="save"><div class="agent-toolbar"><h3>{{ editId ? '编辑返程地址' : '新增返程地址' }}</h3><el-button text :disabled="busy" @click="editing = false">取消</el-button></div><fieldset :disabled="busy"><label>地址名称<input v-model="form.label" required maxlength="128" /></label><div class="form-grid"><label>收件人<input v-model="form.contactName" required maxlength="128" /></label><label>联系电话<input v-model="form.contactPhone" required maxlength="64" /></label><label class="form-wide">地址<input v-model="form.addressLine1" required maxlength="255" /></label><label class="form-wide">补充地址<input v-model="form.addressLine2" maxlength="255" /></label><label>城市<input v-model="form.city" required maxlength="128" /></label><label>省 / 州<input v-model="form.region" maxlength="128" /></label><label>邮编<input v-model="form.postalCode" required maxlength="32" /></label><label>国家 / 地区<input v-model="form.country" required maxlength="128" placeholder="例如 CN、US、HK" /></label></div><label class="agent-checkbox"><input v-model="form.defaultAddress" type="checkbox" />设为默认地址</label></fieldset><button class="btn-primary" :disabled="busy" data-testid="agent-save-address">保存地址</button></form></section></template>
