<script setup lang="ts">
import { computed, onBeforeUnmount, reactive, ref, watch } from 'vue'
import { tx } from '@/i18n'
import { CREDIT_CURRENCIES, getEnterpriseCreditSummary, quoteCompanyCredit, previewEnterpriseCreditConversion, convertEnterpriseCreditBalances, quoteEnterpriseCreditRecharge, getCreditApiError, type CreditQuote, type CreditConversionPreview, type EnterpriseCreditSummary } from '@/api/nxr/enterpriseCredit'
import { getWalletRecharges, getWalletTransactions, reviewWalletRecharge } from '@/api/nxr/merchantWallet'
import { requestPartnerRecharge, type PartnerRecharge } from '@/api/nxr/partners'
import { useEnterpriseCreditQuote } from '@/composables/useEnterpriseCreditQuote'
import { emptyAgentPage, formatMoney, formatPoints, agentDateLabel, agentStatusLabel, type AgentTransaction } from '@/views/nxr/agent-workbench/lib/agentWorkbench'
const props = defineProps<{ companyId: number; canRecharge?: boolean }>()
const emit = defineEmits<{ changed: [] }>()
const summary = ref<EnterpriseCreditSummary | null>(null), recharges = ref(emptyAgentPage<PartnerRecharge>()), transactions = ref(emptyAgentPage<AgentTransaction>())
const loading = ref(false), busy = ref(false), error = ref(''), success = ref(''), status = ref('pending'), currency = ref('PTS')
const ledgerCurrencies = ['PTS', ...CREDIT_CURRENCIES]
const legacy = computed(() => summary.value?.legacyBalances.filter(item => Number(item.balance) !== 0) || [])
const rechargeOpen = ref(false), recharge = reactive({ currencyCode: 'CNY', amount: '', providerCode: 'bank_transfer', payerReference: '', proofReference: '' })
const rechargeQuote = useEnterpriseCreditQuote(() => ({currencyCode:recharge.currencyCode,amount:recharge.amount,enabled:rechargeOpen.value}), value => quoteCompanyCredit(props.companyId,value))
const reviewOpen = ref(false), review = reactive({ item: null as PartnerRecharge | null, approved: true, providerTransactionId: '', note: '' }), reviewQuote = ref<CreditQuote | null>(null), reviewLoading = ref(false)
const conversionOpen = ref(false), conversion = ref<CreditConversionPreview | null>(null), conversionNote = ref(''), conversionAccepted = ref(false)
let active = true, generation = 0, txGeneration = 0, rechargeGeneration = 0, reviewGeneration = 0
const attempts = new Map<string,{fingerprint:string;key:string}>()
function message(e: unknown) { return getCreditApiError(e).message || tx('The operation could not be completed. Please try again.') }
async function loadTransactions(page=1) { const current=++txGeneration,id=props.companyId; try { const result=await getWalletTransactions(id,{currencyCode:currency.value,page,pageSize:20});if(active&&id===props.companyId&&current===txGeneration)transactions.value=result.data } catch(e){if(active&&current===txGeneration)error.value=message(e)} }
async function loadRecharges(page=1) { const current=++rechargeGeneration,id=props.companyId; try { const result=await getWalletRecharges(id,{status:status.value||undefined,page,pageSize:20});if(active&&id===props.companyId&&current===rechargeGeneration)recharges.value=result.data } catch(e){if(active&&current===rechargeGeneration)error.value=message(e)} }
async function refresh() { const current=++generation,id=props.companyId;loading.value=true;error.value='';try { const value=await getEnterpriseCreditSummary(id);if(active&&current===generation)summary.value=value;await Promise.all([loadRecharges(),loadTransactions()]) }catch(e){if(active&&current===generation)error.value=message(e)}finally{if(active&&current===generation)loading.value=false} }
async function mutate(name:string,payload:object,action:(key:string)=>Promise<unknown>,done:()=>void,notice:string) {
  if(busy.value)return false
  const id=props.companyId,fingerprint=JSON.stringify(payload);let attempt=attempts.get(name)
  if(!attempt||attempt.fingerprint!==fingerprint){attempt={fingerprint,key:crypto.randomUUID()};attempts.set(name,attempt)}
  busy.value=true;error.value='';success.value=''
  try { await action(attempt.key);attempts.delete(name);if(active&&id===props.companyId){done();success.value=notice;await refresh();emit('changed')}return true }
  catch(e){if(active&&id===props.companyId)error.value=message(e);return false}
  finally{busy.value=false}
}
function startRecharge() { Object.assign(recharge,{currencyCode:'CNY',amount:'',providerCode:'bank_transfer',payerReference:'',proofReference:''});rechargeOpen.value=true;error.value='' }
async function saveRecharge() {
  if(!props.canRecharge||!rechargeQuote.valid.value||!rechargeQuote.quote.value)return
  const id=props.companyId,payload={...recharge,settingsVersion:rechargeQuote.quote.value.settingsVersion}
  if(!await mutate(`recharge:${id}`,payload,key=>requestPartnerRecharge(id,{...payload,requestKey:key}),()=>{rechargeOpen.value=false},tx('Top-up request recorded, pending payment verification.')))rechargeQuote.invalidate()
}
async function startReview(item:PartnerRecharge,approved:boolean) {
  const current=++reviewGeneration,id=props.companyId
  Object.assign(review,{item,approved,providerTransactionId:'',note:''});reviewQuote.value=item.creditQuote||null;reviewLoading.value=false;reviewOpen.value=true;error.value=''
  if(approved&&!item.creditQuote){reviewLoading.value=true;try{const value=await quoteCompanyCredit(id,{currencyCode:item.currencyCode,amount:item.amount});if(active&&current===reviewGeneration)reviewQuote.value=value}catch(e){if(active&&current===reviewGeneration)error.value=message(e)}finally{if(active&&current===reviewGeneration)reviewLoading.value=false}}
}
async function pinReviewQuote() {
  if(!review.item||!reviewQuote.value||review.item.creditQuote||reviewLoading.value)return
  const id=props.companyId,item=review.item,displayed=reviewQuote.value
  const pinned = await mutate(`pin:${id}:${item.id}`,{settingsVersion:displayed.settingsVersion},async()=>{
    const pinned=await quoteEnterpriseCreditRecharge(id,item.id,displayed.settingsVersion)
    if(active&&id===props.companyId&&review.item?.id===item.id){review.item.creditQuote=pinned;reviewQuote.value=pinned}
  },()=>{},tx('Credit conversion confirmed for this top-up. Verify payment before approval.'))
  if(!pinned)reviewQuote.value=null
}
async function saveReview() {
  const id=props.companyId,item=review.item
  if(!item||!review.note.trim()||(review.approved&&(!item.creditQuote||!review.providerTransactionId.trim())))return
  const approved=review.approved,payload={providerTransactionId:review.providerTransactionId.trim(),note:review.note.trim()}
  await mutate(`review:${id}:${item.id}`,{...payload,approved},()=>reviewWalletRecharge(id,item.id,approved,payload),()=>{reviewOpen.value=false},approved?tx('Top-up approved and credited.'):tx('Top-up rejected.'))
}
async function startConversion() {
  conversion.value=null;conversionNote.value='';conversionAccepted.value=false;conversionOpen.value=true;error.value='';const id=props.companyId,current=generation
  busy.value=true;try{const value=await previewEnterpriseCreditConversion(id);if(active&&id===props.companyId&&current===generation)conversion.value=value}catch(e){if(active&&id===props.companyId)error.value=message(e)}finally{busy.value=false}
}
async function confirmConversion() {
  if(!conversion.value||!conversionAccepted.value||!conversion.value.balances.length||!conversionNote.value.trim())return
  const id=props.companyId,preview=conversion.value,payload={expectedVersion:preview.settingsVersion,balances:preview.balances.map(item=>({currencyCode:item.currencyCode,balance:item.balance})),note:conversionNote.value.trim()}
  if(!await mutate(`conversion:${id}`,payload,key=>convertEnterpriseCreditBalances(id,{...payload,idempotencyKey:key}),()=>{conversionOpen.value=false},tx('Historical balances converted to enterprise credits. Past transactions are retained.'))){conversion.value=null;conversionAccepted.value=false}
}
watch(()=>props.companyId,()=>{generation++;txGeneration++;rechargeGeneration++;reviewGeneration++;summary.value=null;transactions.value=emptyAgentPage();recharges.value=emptyAgentPage();rechargeOpen.value=false;reviewOpen.value=false;conversionOpen.value=false;reviewQuote.value=null;reviewLoading.value=false;currency.value='PTS';void refresh()},{immediate:true})
onBeforeUnmount(()=>{active=false;generation++;txGeneration++;rechargeGeneration++;reviewGeneration++})
</script>
<template>
  <section v-loading="loading" data-testid="enterprise-credit-finance">
    <el-alert v-if="error" :title="error" type="error" :closable="false"/><el-alert v-if="success" :title="success" type="success" :closable="false"/>
    <div class="finance-heading"><div><h3>{{$tx('Enterprise credits')}}</h3><strong class="credit-total">{{summary?formatPoints(summary.balance):'—'}}</strong></div><div><el-button :disabled="busy" @click="refresh">{{$tx('Refresh')}}</el-button><el-button v-if="canRecharge" type="primary" :disabled="busy" data-testid="partner-open-recharge" @click="startRecharge">{{$tx('Record offline top-up')}}</el-button></div></div>
    <p>{{$tx('One credit balance for all supported payment currencies.')}}</p>
    <section v-if="legacy.length" class="legacy-balances"><h4>{{$tx('Historical currency balances')}}</h4><p>{{$tx('Historical balances remain separate until NXR confirms their conversion. Past transactions are retained.')}}</p><p v-for="item in legacy" :key="item.currencyCode">{{formatMoney(item.balance,item.currencyCode)}}</p><el-button :disabled="busy" data-testid="preview-legacy-conversion" @click="startConversion">{{$tx('Preview balance conversion')}}</el-button></section>
    <div class="finance-heading"><h3>{{$tx('Top-up verification')}}</h3><el-select v-model="status" style="width:180px" @change="loadRecharges()"><el-option :label="$tx('Pending verification')" value="pending"/><el-option :label="$tx('All records')" value=""/><el-option :label="$tx('Credited')" value="confirmed"/><el-option :label="$tx('Rejected')" value="rejected"/></el-select></div>
    <el-table :data="recharges.items" border><el-table-column prop="rechargeNo" :label="$tx('Top-up reference')" min-width="180"/><el-table-column :label="$tx('Payment amount')" min-width="140"><template #default="{row}">{{formatMoney(row.amount,row.currencyCode)}}</template></el-table-column><el-table-column :label="$tx('Enterprise credits')" min-width="170"><template #default="{row}">{{row.creditQuote?formatPoints(row.creditQuote.points):$tx('Historical currency record')}}<small v-if="row.creditQuote">{{$tx('Rate version {version}',{version:row.creditQuote.settingsVersion})}}</small></template></el-table-column><el-table-column :label="$tx('Payment evidence')" min-width="180"><template #default="{row}">{{row.payerReference}}<small>{{row.proofReference}}</small></template></el-table-column><el-table-column :label="$tx('Status')" width="130"><template #default="{row}">{{agentStatusLabel(row.statusCode)}}</template></el-table-column><el-table-column :label="$tx('Actions')" min-width="150"><template #default="{row}"><template v-if="row.statusCode==='pending'"><el-button link type="success" :disabled="busy" @click="startReview(row,true)">{{$tx('Confirm receipt')}}</el-button><el-button link type="danger" :disabled="busy" @click="startReview(row,false)">{{$tx('Reject')}}</el-button></template><span v-else>{{row.reviewNote||'—'}}</span></template></el-table-column></el-table>
    <el-pagination v-if="recharges.total>20" layout="prev,pager,next" :total="recharges.total" :page-size="20" :current-page="recharges.page" @current-change="loadRecharges"/>
    <div class="finance-heading"><h3>{{$tx('Credit and historical transactions')}}</h3><el-select v-model="currency" style="width:210px" @change="loadTransactions()"><el-option v-for="code in ledgerCurrencies" :key="code" :value="code" :label="code==='PTS'?$tx('Enterprise credits'):$tx('Historical {currency}',{currency:code})"/></el-select></div>
    <el-table :data="transactions.items" border><el-table-column :label="$tx('Time')" min-width="160"><template #default="{row}">{{agentDateLabel(row.createdAt)}}</template></el-table-column><el-table-column :label="$tx('Amount')" min-width="150"><template #default="{row}">{{row.directionCode==='debit'?'−':'+'}}{{formatMoney(row.amount,row.currencyCode||currency)}}</template></el-table-column><el-table-column :label="$tx('Balance')" min-width="150"><template #default="{row}">{{formatMoney(row.balanceAfter,row.currencyCode||currency)}}</template></el-table-column><el-table-column :label="$tx('Original payment')" min-width="160"><template #default="{row}">{{row.sourceCurrency&&row.sourceAmount!=null?formatMoney(row.sourceAmount,row.sourceCurrency):'—'}}</template></el-table-column><el-table-column prop="note" :label="$tx('Notes')" min-width="180"/></el-table><el-pagination v-if="transactions.total>20" layout="prev,pager,next" :total="transactions.total" :page-size="20" :current-page="transactions.page" @current-change="loadTransactions"/>
    <el-dialog v-model="rechargeOpen" :title="$tx('Record partner offline top-up')" width="min(600px,94vw)" :close-on-click-modal="false" :show-close="!busy" append-to-body><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-form label-position="top" :disabled="busy" @submit.prevent="saveRecharge"><el-form-item :label="$tx('Payment currency')"><el-select v-model="recharge.currencyCode"><el-option v-for="code in CREDIT_CURRENCIES" :key="code" :label="code" :value="code"/></el-select></el-form-item><el-form-item :label="$tx('Amount')" required><el-input v-model="recharge.amount" type="number" required :min="recharge.currencyCode==='JPY'?1:0.01" :step="recharge.currencyCode==='JPY'?1:0.01"/></el-form-item><el-form-item :label="$tx('Transfer method')"><el-select v-model="recharge.providerCode"><el-option :label="$tx('Bank transfer')" value="bank_transfer"/><el-option :label="$tx('WeChat transfer')" value="wechat_transfer"/><el-option :label="$tx('Alipay transfer')" value="alipay_transfer"/></el-select></el-form-item><el-form-item :label="$tx('Transfer reference')" required><el-input v-model="recharge.payerReference" required maxlength="255"/></el-form-item><el-form-item :label="$tx('Payment evidence notes')"><el-input v-model="recharge.proofReference" maxlength="512"/></el-form-item><div class="credit-quote" aria-live="polite"><p v-if="rechargeQuote.loading.value">{{$tx('Calculating credits…')}}</p><template v-if="rechargeQuote.valid.value&&rechargeQuote.quote.value"><strong>{{formatMoney(rechargeQuote.quote.value.sourceAmount,rechargeQuote.quote.value.sourceCurrency)}} → {{formatPoints(rechargeQuote.quote.value.points)}}</strong><p>{{$tx('Rate version {version}',{version:rechargeQuote.quote.value.settingsVersion})}} · 1 {{rechargeQuote.quote.value.sourceCurrency}} = {{rechargeQuote.quote.value.cnyPerUnit}} CNY · 1 CNY = {{rechargeQuote.quote.value.pointsPerCny}} PTS</p></template><p v-if="rechargeQuote.error.value">{{rechargeQuote.error.value}}</p><el-button :disabled="busy||rechargeQuote.loading.value||!Number(recharge.amount)" @click="rechargeQuote.refresh">{{$tx('Refresh credit quote')}}</el-button></div><p>{{$tx('This records a pending request. Credits are added after payment is verified.')}}</p><div class="finance-actions"><el-button :disabled="busy" @click="rechargeOpen=false">{{$tx('Cancel')}}</el-button><el-button type="primary" native-type="submit" :disabled="busy||!rechargeQuote.valid.value" data-testid="partner-save-recharge">{{$tx('Record pending top-up')}}</el-button></div></el-form></el-dialog>
    <el-dialog v-model="reviewOpen" :title="review.approved?$tx('Confirm partner top-up receipt'):$tx('Reject top-up')" width="min(600px,94vw)" :close-on-click-modal="false" :show-close="!busy" append-to-body><el-alert v-if="error" :title="error" type="error" :closable="false"/><p v-if="review.item">{{review.item.rechargeNo}} · {{formatMoney(review.item.amount,review.item.currencyCode)}}</p><template v-if="review.approved"><div v-loading="reviewLoading" class="credit-quote"><template v-if="reviewQuote"><strong>{{formatPoints(reviewQuote.points)}}</strong><p>{{$tx('Rate version {version}',{version:reviewQuote.settingsVersion})}} · 1 {{reviewQuote.sourceCurrency}} = {{reviewQuote.cnyPerUnit}} CNY · 1 CNY = {{reviewQuote.pointsPerCny}} PTS</p></template><template v-if="!review.item?.creditQuote"><p>{{$tx('This historical pending request has no credit quote. Review and confirm the conversion before approving payment.')}}</p><el-button v-if="reviewQuote" :disabled="busy||reviewLoading" data-testid="pin-recharge-credit-quote" @click="pinReviewQuote">{{$tx('Confirm this credit conversion')}}</el-button><el-button v-else :disabled="busy||reviewLoading" @click="review.item&&startReview(review.item,true)">{{$tx('Refresh credit quote')}}</el-button></template></div><el-alert :title="$tx('Verify that payment has been received. Confirmation credits the company balance.')" type="warning" :closable="false"/></template><el-form label-position="top" :disabled="busy" @submit.prevent="saveReview"><el-form-item v-if="review.approved" :label="$tx('Received payment reference')" required><el-input v-model="review.providerTransactionId" required maxlength="255"/></el-form-item><el-form-item :label="review.approved?$tx('Verification notes'):$tx('Rejection reason')" required><el-input v-model="review.note" required type="textarea" maxlength="2000"/></el-form-item><div class="finance-actions"><el-button :disabled="busy" @click="reviewOpen=false">{{$tx('Cancel')}}</el-button><el-button type="primary" native-type="submit" :disabled="busy||reviewLoading||(review.approved&&!review.item?.creditQuote)" data-testid="partner-confirm-review">{{review.approved?$tx('Confirm receipt'):$tx('Confirm rejection')}}</el-button></div></el-form></el-dialog>
    <el-dialog v-model="conversionOpen" :title="$tx('Convert historical balances')" width="min(680px,94vw)" :close-on-click-modal="false" :show-close="!busy" append-to-body><el-alert v-if="error" :title="error" type="error" :closable="false"/><template v-if="conversion"><p>{{$tx('Rate version {version}',{version:conversion.settingsVersion})}}</p><el-table :data="conversion.balances" border><el-table-column :label="$tx('Historical currency balances')"><template #default="{row}">{{formatMoney(row.balance,row.currencyCode)}}</template></el-table-column><el-table-column :label="$tx('Enterprise credits')"><template #default="{row}">{{formatPoints(row.points)}}</template></el-table-column></el-table><h3>{{$tx('Credits to add')}}: {{formatPoints(conversion.totalPoints)}}</h3><p>{{$tx('The listed currency balances will become zero and the quoted credits will be added. Historical transactions remain unchanged.')}}</p><el-input v-model="conversionNote" type="textarea" maxlength="2000" :placeholder="$tx('Conversion notes (required)')"/><el-checkbox v-model="conversionAccepted" :disabled="busy">{{$tx('I confirm the balances and credit conversion shown above.')}}</el-checkbox></template><el-button v-else :disabled="busy" @click="startConversion">{{$tx('Refresh conversion preview')}}</el-button><template #footer><el-button :disabled="busy" @click="conversionOpen=false">{{$tx('Cancel')}}</el-button><el-button type="primary" :disabled="busy||!conversionAccepted||!conversion?.balances.length||!conversionNote.trim()" data-testid="confirm-legacy-conversion" @click="confirmConversion">{{$tx('Confirm balance conversion')}}</el-button></template></el-dialog>
  </section>
</template>
<style scoped>.finance-heading{display:flex;align-items:center;justify-content:space-between;gap:14px;margin:20px 0}.finance-heading h3{margin:0 0 8px}.credit-total{font-size:28px}.legacy-balances,.credit-quote{padding:18px;border:1px solid var(--el-border-color);border-radius:8px;margin:16px 0}.finance-actions{display:flex;justify-content:flex-end;gap:12px;margin-top:18px}.el-pagination{margin-top:16px}small{display:block;color:var(--el-text-color-secondary);margin-top:5px}.el-checkbox{height:auto;white-space:normal;margin-top:15px}@media(max-width:640px){.finance-heading{align-items:flex-start;flex-direction:column}}</style>
