export { default as BookingPage } from './BookingPage.vue'
export { default as CheckoutPage } from './CheckoutPage.vue'
export { default as DashboardPage } from './DashboardPage.vue'
export { default as LearningPage } from './LearningPage.vue'
export { default as LiveRoomPage } from './LiveRoomPage.vue'
export { default as ResourceManagementPage } from './ResourceManagementPage.vue'
export * from './management'
export * from './workspace'
export * from './solutions'
